<?php

declare(strict_types=1);

namespace Rudashi\GusApi\Services\FullReport;

use Rudashi\GusApi\Contracts\Response;

/**
 * @phpstan-consistent-constructor
 */
class LocalResponse implements Response
{
    public function __construct(
        public readonly string $regon14,
        public readonly string $nazwa,
        public readonly string $adSiedzKraj_Symbol,
        public readonly string $adSiedzWojewodztwo_Symbol,
        public readonly string $adSiedzPowiat_Symbol,
        public readonly string $adSiedzGmina_Symbol,
        public readonly string $adSiedzKodPocztowy,
        public readonly string $adSiedzMiejscowoscPoczty_Symbol,
        public readonly string $adSiedzMiejscowosc_Symbol,
        public readonly string $adSiedzUlica_Symbol,
        public readonly string $adSiedzNumerNieruchomosci,
        public readonly string $adSiedzNumerLokalu,
        public readonly string $adSiedzNietypoweMiejsceLokalizacji,
        public readonly string $adSiedzWojewodztwo_Nazwa,
        public readonly string $adSiedzPowiat_Nazwa,
        public readonly string $adSiedzGmina_Nazwa,
        public readonly string $adSiedzMiejscowosc_Nazwa,
        public readonly string $adSiedzMiejscowoscPoczty_Nazwa,
        public readonly string $adSiedzUlica_Nazwa,
        public readonly string $dataPowstania,
        public readonly string $dataRozpoczeciaDzialalnosci,
        public readonly string $dataWpisuDoRegon,
        public readonly string $dataZawieszeniaDzialalnosci,
        public readonly string $dataWznowieniaDzialalnosci,
        public readonly string $dataZakonczeniaDzialalnosci,
        public readonly string $dataSkresleniaZRegon,
        public readonly string $numerWrejestrzeEwidencji = '',
        public readonly string $dataWpisuDoRejestruEwidencji = '',
        public readonly string $adSiedzKraj_Nazwa = '',
        public readonly string $formaFinansowania_Symbol = '',
        public readonly string $formaFinansowania_Nazwa = '',
        public readonly string $organRejestrowy_Symbol = '',
        public readonly string $organRejestrowy_Nazwa = '',
        public readonly string $rodzajRejestruEwidencji_Symbol = '',
        public readonly string $rodzajRejestruEwidencji_Nazwa = '',
        public readonly string $rodzajRejestru_Symbol = '',
        public readonly string $rodzajRejestru_Nazwa = '',
        public readonly string $dataZaistnieniaZmiany = '',
        public readonly string $niePodjetoDzialalnosci = '',
        public readonly string $silosID = '',
        public readonly string $silos_Symbol = '',
        public readonly string $silos_Nazwa = '',
    ) {
    }

    public function result(): array
    {
        return (array) $this;
    }

    public static function forCompany(
        string $lokpraw_regon14,
        string $lokpraw_nazwa,
        string $lokpraw_adSiedzKraj_Symbol,
        string $lokpraw_adSiedzWojewodztwo_Symbol,
        string $lokpraw_adSiedzPowiat_Symbol,
        string $lokpraw_adSiedzGmina_Symbol,
        string $lokpraw_adSiedzKodPocztowy,
        string $lokpraw_adSiedzMiejscowoscPoczty_Symbol,
        string $lokpraw_adSiedzMiejscowosc_Symbol,
        string $lokpraw_adSiedzUlica_Symbol,
        string $lokpraw_adSiedzNumerNieruchomosci,
        string $lokpraw_adSiedzNumerLokalu,
        string $lokpraw_adSiedzNietypoweMiejsceLokalizacji,
        string $lokpraw_adSiedzWojewodztwo_Nazwa,
        string $lokpraw_adSiedzPowiat_Nazwa,
        string $lokpraw_adSiedzGmina_Nazwa,
        string $lokpraw_adSiedzMiejscowosc_Nazwa,
        string $lokpraw_adSiedzMiejscowoscPoczty_Nazwa,
        string $lokpraw_adSiedzUlica_Nazwa,
        string $lokpraw_dataPowstania,
        string $lokpraw_dataRozpoczeciaDzialalnosci,
        string $lokpraw_dataWpisuDoRegon,
        string $lokpraw_dataZawieszeniaDzialalnosci,
        string $lokpraw_dataWznowieniaDzialalnosci,
        string $lokpraw_dataZakonczeniaDzialalnosci,
        string $lokpraw_dataSkresleniaZRegon,
        string $lokpraw_numerWrejestrzeEwidencji = '',
        string $lokpraw_dataWpisuDoRejestruEwidencji = '',
        string $lokpraw_adSiedzKraj_Nazwa = '',
        string $lokpraw_formaFinansowania_Symbol = '',
        string $lokpraw_organRejestrowy_Symbol = '',
        string $lokpraw_rodzajRejestruEwidencji_Symbol = '',
        string $lokpraw_formaFinansowania_Nazwa = '',
        string $lokpraw_organRejestrowy_Nazwa = '',
        string $lokpraw_rodzajRejestruEwidencji_Nazwa = '',
        string $lokpraw_dataZaistnieniaZmiany = '',
        string $lokpraw_silosID = '',
        string $lokpraw_silos_Symbol = '',
    ): static {
        return new static(
            regon14: $lokpraw_regon14,
            nazwa: $lokpraw_nazwa,
            adSiedzKraj_Symbol: $lokpraw_adSiedzKraj_Symbol,
            adSiedzWojewodztwo_Symbol: $lokpraw_adSiedzWojewodztwo_Symbol,
            adSiedzPowiat_Symbol: $lokpraw_adSiedzPowiat_Symbol,
            adSiedzGmina_Symbol: $lokpraw_adSiedzGmina_Symbol,
            adSiedzKodPocztowy: $lokpraw_adSiedzKodPocztowy,
            adSiedzMiejscowoscPoczty_Symbol: $lokpraw_adSiedzMiejscowoscPoczty_Symbol,
            adSiedzMiejscowosc_Symbol: $lokpraw_adSiedzMiejscowosc_Symbol,
            adSiedzUlica_Symbol: $lokpraw_adSiedzUlica_Symbol,
            adSiedzNumerNieruchomosci: $lokpraw_adSiedzNumerNieruchomosci,
            adSiedzNumerLokalu: $lokpraw_adSiedzNumerLokalu,
            adSiedzNietypoweMiejsceLokalizacji: $lokpraw_adSiedzNietypoweMiejsceLokalizacji,
            adSiedzWojewodztwo_Nazwa: $lokpraw_adSiedzWojewodztwo_Nazwa,
            adSiedzPowiat_Nazwa: $lokpraw_adSiedzPowiat_Nazwa,
            adSiedzGmina_Nazwa: $lokpraw_adSiedzGmina_Nazwa,
            adSiedzMiejscowosc_Nazwa: $lokpraw_adSiedzMiejscowosc_Nazwa,
            adSiedzMiejscowoscPoczty_Nazwa: $lokpraw_adSiedzMiejscowoscPoczty_Nazwa,
            adSiedzUlica_Nazwa: $lokpraw_adSiedzUlica_Nazwa,
            dataPowstania: $lokpraw_dataPowstania,
            dataRozpoczeciaDzialalnosci: $lokpraw_dataRozpoczeciaDzialalnosci,
            dataWpisuDoRegon: $lokpraw_dataWpisuDoRegon,
            dataZawieszeniaDzialalnosci: $lokpraw_dataZawieszeniaDzialalnosci,
            dataWznowieniaDzialalnosci: $lokpraw_dataWznowieniaDzialalnosci,
            dataZakonczeniaDzialalnosci: $lokpraw_dataZakonczeniaDzialalnosci,
            dataSkresleniaZRegon: $lokpraw_dataSkresleniaZRegon,
            numerWrejestrzeEwidencji: $lokpraw_numerWrejestrzeEwidencji,
            dataWpisuDoRejestruEwidencji: $lokpraw_dataWpisuDoRejestruEwidencji,
            adSiedzKraj_Nazwa: $lokpraw_adSiedzKraj_Nazwa,
            formaFinansowania_Symbol: $lokpraw_formaFinansowania_Symbol,
            formaFinansowania_Nazwa: $lokpraw_formaFinansowania_Nazwa,
            organRejestrowy_Symbol: $lokpraw_organRejestrowy_Symbol,
            organRejestrowy_Nazwa: $lokpraw_organRejestrowy_Nazwa,
            rodzajRejestruEwidencji_Symbol: $lokpraw_rodzajRejestruEwidencji_Symbol,
            rodzajRejestruEwidencji_Nazwa: $lokpraw_rodzajRejestruEwidencji_Nazwa,
            dataZaistnieniaZmiany: $lokpraw_dataZaistnieniaZmiany,
            silosID: $lokpraw_silosID,
            silos_Symbol: $lokpraw_silos_Symbol,
        );
    }

    public static function forPerson(
        string $lokfiz_regon14,
        string $lokfiz_nazwa,
        string $lokfiz_silosID,
        string $lokfiz_adSiedzKraj_Symbol,
        string $lokfiz_adSiedzWojewodztwo_Symbol,
        string $lokfiz_adSiedzPowiat_Symbol,
        string $lokfiz_adSiedzGmina_Symbol,
        string $lokfiz_adSiedzKodPocztowy,
        string $lokfiz_adSiedzMiejscowoscPoczty_Symbol,
        string $lokfiz_adSiedzMiejscowosc_Symbol,
        string $lokfiz_adSiedzUlica_Symbol,
        string $lokfiz_adSiedzNumerNieruchomosci,
        string $lokfiz_adSiedzNumerLokalu,
        string $lokfiz_adSiedzNietypoweMiejsceLokalizacji,
        string $lokfiz_adSiedzWojewodztwo_Nazwa,
        string $lokfiz_adSiedzPowiat_Nazwa,
        string $lokfiz_adSiedzGmina_Nazwa,
        string $lokfiz_adSiedzMiejscowosc_Nazwa,
        string $lokfiz_adSiedzMiejscowoscPoczty_Nazwa,
        string $lokfiz_adSiedzUlica_Nazwa,
        string $lokfiz_dataPowstania,
        string $lokfiz_dataRozpoczeciaDzialalnosci,
        string $lokfiz_dataWpisuDoRegon,
        string $lokfiz_dataZawieszeniaDzialalnosci,
        string $lokfiz_dataWznowieniaDzialalnosci,
        string $lokfiz_dataZakonczeniaDzialalnosci,
        string $lokfiz_dataSkresleniaZRegon,
        string $lokfiz_silos_Symbol = '',
        string $lokfiz_silos_Nazwa = '',
        string $lokfiz_dataZaistnieniaZmiany = '',
        string $lokfiz_adSiedzKraj_Nazwa = '',
        string $lokfiz_FormaFinansowania_Symbol = '',
        string $lokfiz_FormaFinansowania_Nazwa = '',
        string $lokfiz_dataWpisuDoRejestruEwidencji = '',
        string $lokfiz_numerwRejestrzeEwidencji = '',
        string $lokfiz_OrganRejestrowy_Symbol = '',
        string $lokfiz_OrganRejestrowy_Nazwa = '',
        string $lokfiz_RodzajRejestru_Symbol = '',
        string $lokfiz_RodzajRejestru_Nazwa = '',
        string $lokfizC_NiePodjetoDzialalnosci = '',
    ): static {
        return new static(
            regon14: $lokfiz_regon14,
            nazwa: $lokfiz_nazwa,
            adSiedzKraj_Symbol: $lokfiz_adSiedzKraj_Symbol,
            adSiedzWojewodztwo_Symbol: $lokfiz_adSiedzWojewodztwo_Symbol,
            adSiedzPowiat_Symbol: $lokfiz_adSiedzPowiat_Symbol,
            adSiedzGmina_Symbol: $lokfiz_adSiedzGmina_Symbol,
            adSiedzKodPocztowy: $lokfiz_adSiedzKodPocztowy,
            adSiedzMiejscowoscPoczty_Symbol: $lokfiz_adSiedzMiejscowoscPoczty_Symbol,
            adSiedzMiejscowosc_Symbol: $lokfiz_adSiedzMiejscowosc_Symbol,
            adSiedzUlica_Symbol: $lokfiz_adSiedzUlica_Symbol,
            adSiedzNumerNieruchomosci: $lokfiz_adSiedzNumerNieruchomosci,
            adSiedzNumerLokalu: $lokfiz_adSiedzNumerLokalu,
            adSiedzNietypoweMiejsceLokalizacji: $lokfiz_adSiedzNietypoweMiejsceLokalizacji,
            adSiedzWojewodztwo_Nazwa: $lokfiz_adSiedzWojewodztwo_Nazwa,
            adSiedzPowiat_Nazwa: $lokfiz_adSiedzPowiat_Nazwa,
            adSiedzGmina_Nazwa: $lokfiz_adSiedzGmina_Nazwa,
            adSiedzMiejscowosc_Nazwa: $lokfiz_adSiedzMiejscowosc_Nazwa,
            adSiedzMiejscowoscPoczty_Nazwa: $lokfiz_adSiedzMiejscowoscPoczty_Nazwa,
            adSiedzUlica_Nazwa: $lokfiz_adSiedzUlica_Nazwa,
            dataPowstania: $lokfiz_dataPowstania,
            dataRozpoczeciaDzialalnosci: $lokfiz_dataRozpoczeciaDzialalnosci,
            dataWpisuDoRegon: $lokfiz_dataWpisuDoRegon,
            dataZawieszeniaDzialalnosci: $lokfiz_dataZawieszeniaDzialalnosci,
            dataWznowieniaDzialalnosci: $lokfiz_dataWznowieniaDzialalnosci,
            dataZakonczeniaDzialalnosci: $lokfiz_dataZakonczeniaDzialalnosci,
            dataSkresleniaZRegon: $lokfiz_dataSkresleniaZRegon,
            numerWrejestrzeEwidencji: $lokfiz_numerwRejestrzeEwidencji,
            dataWpisuDoRejestruEwidencji: $lokfiz_dataWpisuDoRejestruEwidencji,
            adSiedzKraj_Nazwa: $lokfiz_adSiedzKraj_Nazwa,
            formaFinansowania_Symbol: $lokfiz_FormaFinansowania_Symbol,
            formaFinansowania_Nazwa: $lokfiz_FormaFinansowania_Nazwa,
            organRejestrowy_Symbol: $lokfiz_OrganRejestrowy_Symbol,
            organRejestrowy_Nazwa: $lokfiz_OrganRejestrowy_Nazwa,
            rodzajRejestru_Symbol: $lokfiz_RodzajRejestru_Symbol,
            rodzajRejestru_Nazwa: $lokfiz_RodzajRejestru_Nazwa,
            dataZaistnieniaZmiany: $lokfiz_dataZaistnieniaZmiany,
            niePodjetoDzialalnosci: $lokfizC_NiePodjetoDzialalnosci,
            silosID: $lokfiz_silosID,
            silos_Symbol: $lokfiz_silos_Symbol,
            silos_Nazwa: $lokfiz_silos_Nazwa,
        );
    }
}
